import type { User, Employee, LeaveRequest, AttendanceRecord, PayrollRecord } from "./types"

export const currentUser: User = {
  id: "1",
  name: "Sarah Johnson",
  email: "sarah.johnson@dayflow.com",
  role: "employee",
  department: "Engineering",
  position: "Senior Developer",
  joinDate: "2022-03-15",
  avatar: "/professional-woman-avatar.png",
}

export const adminUser: User = {
  id: "0",
  name: "Michael Chen",
  email: "michael.chen@dayflow.com",
  role: "admin",
  department: "Human Resources",
  position: "HR Manager",
  joinDate: "2020-01-10",
  avatar: "/professional-man-avatar.png",
}

export const employees: Employee[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@dayflow.com",
    phone: "+1 (555) 123-4567",
    department: "Engineering",
    position: "Senior Developer",
    joinDate: "2022-03-15",
    status: "active",
    salary: 95000,
  },
  {
    id: "2",
    name: "James Wilson",
    email: "james.wilson@dayflow.com",
    phone: "+1 (555) 234-5678",
    department: "Design",
    position: "UI/UX Designer",
    joinDate: "2021-06-20",
    status: "active",
    salary: 82000,
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily.davis@dayflow.com",
    phone: "+1 (555) 345-6789",
    department: "Marketing",
    position: "Marketing Manager",
    joinDate: "2020-09-01",
    status: "on-leave",
    salary: 88000,
  },
  {
    id: "4",
    name: "Robert Brown",
    email: "robert.brown@dayflow.com",
    phone: "+1 (555) 456-7890",
    department: "Engineering",
    position: "DevOps Engineer",
    joinDate: "2023-01-10",
    status: "active",
    salary: 92000,
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.anderson@dayflow.com",
    phone: "+1 (555) 567-8901",
    department: "Finance",
    position: "Financial Analyst",
    joinDate: "2022-07-25",
    status: "active",
    salary: 78000,
  },
  {
    id: "6",
    name: "David Martinez",
    email: "david.martinez@dayflow.com",
    phone: "+1 (555) 678-9012",
    department: "Engineering",
    position: "Junior Developer",
    joinDate: "2024-02-01",
    status: "active",
    salary: 65000,
  },
]

export const leaveRequests: LeaveRequest[] = [
  {
    id: "lr-1",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    type: "annual",
    startDate: "2025-01-20",
    endDate: "2025-01-24",
    status: "pending",
    remarks: "Family vacation",
  },
  {
    id: "lr-2",
    employeeId: "2",
    employeeName: "James Wilson",
    type: "sick",
    startDate: "2025-01-15",
    endDate: "2025-01-16",
    status: "approved",
    remarks: "Doctor appointment",
    approverRemarks: "Approved. Get well soon!",
  },
  {
    id: "lr-3",
    employeeId: "3",
    employeeName: "Emily Davis",
    type: "personal",
    startDate: "2025-01-10",
    endDate: "2025-01-10",
    status: "rejected",
    remarks: "Personal matters",
    approverRemarks: "Conflicts with quarterly review deadline",
  },
  {
    id: "lr-4",
    employeeId: "4",
    employeeName: "Robert Brown",
    type: "annual",
    startDate: "2025-02-01",
    endDate: "2025-02-05",
    status: "pending",
    remarks: "Winter break",
  },
]

export const attendanceRecords: AttendanceRecord[] = [
  { id: "a-1", date: "2025-01-03", checkIn: "09:02", checkOut: "18:15", status: "present", workHours: 9.2 },
  { id: "a-2", date: "2025-01-02", checkIn: "08:55", checkOut: "17:45", status: "present", workHours: 8.8 },
  { id: "a-3", date: "2025-01-01", status: "holiday" },
  { id: "a-4", date: "2024-12-31", checkIn: "09:30", checkOut: "13:00", status: "half-day", workHours: 3.5 },
  { id: "a-5", date: "2024-12-30", checkIn: "09:00", checkOut: "18:00", status: "present", workHours: 9 },
  { id: "a-6", date: "2024-12-29", status: "leave" },
  { id: "a-7", date: "2024-12-28", status: "absent" },
]

export const payrollRecords: PayrollRecord[] = [
  {
    id: "pr-1",
    employeeId: "1",
    month: "December 2024",
    basicSalary: 7916.67,
    allowances: 500,
    deductions: 850,
    netSalary: 7566.67,
    status: "paid",
  },
  {
    id: "pr-2",
    employeeId: "1",
    month: "November 2024",
    basicSalary: 7916.67,
    allowances: 500,
    deductions: 850,
    netSalary: 7566.67,
    status: "paid",
  },
  {
    id: "pr-3",
    employeeId: "1",
    month: "January 2025",
    basicSalary: 7916.67,
    allowances: 500,
    deductions: 850,
    netSalary: 7566.67,
    status: "pending",
  },
]

export const notifications = [
  {
    id: "n-1",
    title: "Leave request approved",
    message: "Your leave request for Jan 20-24 has been approved.",
    time: "2 hours ago",
    read: false,
    type: "leave",
  },
  {
    id: "n-2",
    title: "Payroll processed",
    message: "December 2024 salary has been credited to your account.",
    time: "1 day ago",
    read: false,
    type: "payroll",
  },
  {
    id: "n-3",
    title: "Policy update",
    message: "New remote work policy has been published.",
    time: "3 days ago",
    read: true,
    type: "policy",
  },
]
